baseurl: '/'
permalink: pretty
title: 'DuoHives'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"



sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
